#+startup: nofold

* Table of Contents :TOC:
- [[geo-xdg]]
  - [[Endpoints]]
    - [[geo-xdg-last-location]]
    - [[geo-xdg-changed-hooks]]
  - [[Location Format]]
  - [[User Customization]]
- [[geo-xdg-solar]]
  - [[Using geo-xdg-solar]]

* geo-xdg
  ~geo-xdg~ is an Emacs Lisp library for interfacing with the XDG
  GeoClue geolocation API.  There are 2 entry-points for using the API:
  <<Endpoints>>
  <<geo-xdg-last-location>>
  - ~geo-xdg-last-location~ ::
    This variable stores the last recieved location, in a format
    described inside [[Location Format]].  It may be nil if no location
    exists.
  <<geo-xdg-changed-hooks>>
  - ~geo-xdg-changed-hooks~ ::
    This hook stores a list of functions that accept a single argument
    ~LOCATION~, which should be the new location.  The functions are
    called whenever the current location is changed.

    To use geo-xdg, Emacs must be built with Dbus support.
** Location Format
   Locations in geo-xdg are guaranteed to be an alist, with the following elements:

   - ~lat~ :: The latitude of this location.  Always non-nil.
   - ~lon~ :: The longitude of this location.  Always non-nil.
   - ~alt~ :: The altitude of this location in metres.  May be nil.
   - ~speed~ :: The speed the device is traveling at.  May be nil.
   - ~description~ :: A short description of this location.  May be nil.
** User Customization
   Certain aspects of geo-xdg can be customized by users via the following
   variables:

   - ~geo-xdg-cache-function~ ::
     A function that should return a cached location, or nil if none exists.
     The default value is ~geo-xdg-get-cache~.
   - ~geo-xdg-save-cache-function~ ::
     A function that accepts a single location value,
     which should be saved into the cache.

* geo-xdg-solar
  ~geo-xdg-solar~ is a package that sets ~calendar-latitude~
  and ~calendar-longitude~ to the current location provided by
  geo-xdg.  When ~geo-xdg-solar~ is activated, the default cache
  function will also consider ~calendar-latitude~ and
  ~calendar-longitude~, and those variables will be set to the
  appropriate values whenever the location is changed.
  <<Using geo-xdg-solar>>
  To use geo-xdg-solar, place the following code in your initialization
  files, and place geo-xdg and geo-xdg-solar in your ~load-path~:
#+begin_src elisp
(require 'geo-xdg-solar)
#+end_src
